# Generated by Django 5.2.5 on 2025-08-14 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, to='core.branch'),
            preserve_default=False,
        ),
    ]
