# Generated by Django 5.2.5 on 2025-08-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_role_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='title',
        ),
    ]
