# Generated by Django 5.2.5 on 2025-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userprofile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extension',
            field=models.IntegerField(default=555, max_length=3),
            preserve_default=False,
        ),
    ]
