# Generated by Django 5.2.5 on 2025-08-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_region_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='extension',
            field=models.IntegerField(),
        ),
    ]
