# Generated by Django 5.2.5 on 2025-08-21 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_branch_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='core.region'),
        ),
    ]
