# Generated by Django 5.2.5 on 2025-08-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_department_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(default='fuckyou', unique=True),
        ),
    ]
