# Generated by Django 5.2.5 on 2025-08-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_department_managers'),
        ('documents', '0006_document_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.department'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
