# Generated by Django 5.2.5 on 2025-08-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileviewer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
