# Generated by Django 5.2.5 on 2025-08-20 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='assetmanager.status'),
        ),
    ]
